name: ubuntu
on: [push]
jobs:
  setup:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: lithium_test
        ports:
          - 32768:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps: 
      - uses: actions/checkout@v2
      - uses: getong/mariadb-action@v1.1
        with:
          host port: 14550
          mysql root password: lithium_test
          mysql database: mysql_test
      - run: >
          sudo apt-get update && 
          sudo apt-get install -yq libboost-context-dev clang-9 
          libboost-dev wget libmariadb-dev libpq-dev libcurl4-openssl-dev 
  
      - run: cd $GITHUB_WORKSPACE && cmake . -DCMAKE_CXX_COMPILE=g++ && make -j3 && ctest  
      - run: cd $GITHUB_WORKSPACE && cmake . -DCMAKE_CXX_COMPILE=clang++ && make -j3 && ctest  
